/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingsRouteImport } from './routes/trainings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrainingsIdRouteImport } from './routes/trainings.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrainingsRouteImport } from './routes/admin.trainings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminTrainingsNewRouteImport } from './routes/admin.trainings.new'
import { Route as TrainingsIdLessonLessonIdRouteImport } from './routes/trainings.$id.lesson.$lessonId'
import { Route as AdminTrainingsEditIdRouteImport } from './routes/admin.trainings.edit.$id'

const TrainingsRoute = TrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsIdRoute = TrainingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TrainingsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingsRoute = AdminTrainingsRouteImport.update({
  id: '/admin/trainings',
  path: '/admin/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingsNewRoute = AdminTrainingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminTrainingsRoute,
} as any)
const TrainingsIdLessonLessonIdRoute =
  TrainingsIdLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => TrainingsIdRoute,
  } as any)
const AdminTrainingsEditIdRoute = AdminTrainingsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminTrainingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/trainings': typeof TrainingsRouteWithChildren
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/trainings': typeof AdminTrainingsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/trainings/$id': typeof TrainingsIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/trainings/new': typeof AdminTrainingsNewRoute
  '/admin/trainings/edit/$id': typeof AdminTrainingsEditIdRoute
  '/trainings/$id/lesson/$lessonId': typeof TrainingsIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/trainings': typeof TrainingsRouteWithChildren
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/trainings': typeof AdminTrainingsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/trainings/$id': typeof TrainingsIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/trainings/new': typeof AdminTrainingsNewRoute
  '/admin/trainings/edit/$id': typeof AdminTrainingsEditIdRoute
  '/trainings/$id/lesson/$lessonId': typeof TrainingsIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/trainings': typeof TrainingsRouteWithChildren
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/trainings': typeof AdminTrainingsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/trainings/$id': typeof TrainingsIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/trainings/new': typeof AdminTrainingsNewRoute
  '/admin/trainings/edit/$id': typeof AdminTrainingsEditIdRoute
  '/trainings/$id/lesson/$lessonId': typeof TrainingsIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/progress'
    | '/trainings'
    | '/admin/departments'
    | '/admin/reports'
    | '/admin/trainings'
    | '/admin/users'
    | '/trainings/$id'
    | '/admin/'
    | '/admin/trainings/new'
    | '/admin/trainings/edit/$id'
    | '/trainings/$id/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/progress'
    | '/trainings'
    | '/admin/departments'
    | '/admin/reports'
    | '/admin/trainings'
    | '/admin/users'
    | '/trainings/$id'
    | '/admin'
    | '/admin/trainings/new'
    | '/admin/trainings/edit/$id'
    | '/trainings/$id/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/progress'
    | '/trainings'
    | '/admin/departments'
    | '/admin/reports'
    | '/admin/trainings'
    | '/admin/users'
    | '/trainings/$id'
    | '/admin/'
    | '/admin/trainings/new'
    | '/admin/trainings/edit/$id'
    | '/trainings/$id/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  TrainingsRoute: typeof TrainingsRouteWithChildren
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTrainingsRoute: typeof AdminTrainingsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings/$id': {
      id: '/trainings/$id'
      path: '/$id'
      fullPath: '/trainings/$id'
      preLoaderRoute: typeof TrainingsIdRouteImport
      parentRoute: typeof TrainingsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainings': {
      id: '/admin/trainings'
      path: '/admin/trainings'
      fullPath: '/admin/trainings'
      preLoaderRoute: typeof AdminTrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainings/new': {
      id: '/admin/trainings/new'
      path: '/new'
      fullPath: '/admin/trainings/new'
      preLoaderRoute: typeof AdminTrainingsNewRouteImport
      parentRoute: typeof AdminTrainingsRoute
    }
    '/trainings/$id/lesson/$lessonId': {
      id: '/trainings/$id/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/trainings/$id/lesson/$lessonId'
      preLoaderRoute: typeof TrainingsIdLessonLessonIdRouteImport
      parentRoute: typeof TrainingsIdRoute
    }
    '/admin/trainings/edit/$id': {
      id: '/admin/trainings/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/trainings/edit/$id'
      preLoaderRoute: typeof AdminTrainingsEditIdRouteImport
      parentRoute: typeof AdminTrainingsRoute
    }
  }
}

interface TrainingsIdRouteChildren {
  TrainingsIdLessonLessonIdRoute: typeof TrainingsIdLessonLessonIdRoute
}

const TrainingsIdRouteChildren: TrainingsIdRouteChildren = {
  TrainingsIdLessonLessonIdRoute: TrainingsIdLessonLessonIdRoute,
}

const TrainingsIdRouteWithChildren = TrainingsIdRoute._addFileChildren(
  TrainingsIdRouteChildren,
)

interface TrainingsRouteChildren {
  TrainingsIdRoute: typeof TrainingsIdRouteWithChildren
}

const TrainingsRouteChildren: TrainingsRouteChildren = {
  TrainingsIdRoute: TrainingsIdRouteWithChildren,
}

const TrainingsRouteWithChildren = TrainingsRoute._addFileChildren(
  TrainingsRouteChildren,
)

interface AdminTrainingsRouteChildren {
  AdminTrainingsNewRoute: typeof AdminTrainingsNewRoute
  AdminTrainingsEditIdRoute: typeof AdminTrainingsEditIdRoute
}

const AdminTrainingsRouteChildren: AdminTrainingsRouteChildren = {
  AdminTrainingsNewRoute: AdminTrainingsNewRoute,
  AdminTrainingsEditIdRoute: AdminTrainingsEditIdRoute,
}

const AdminTrainingsRouteWithChildren = AdminTrainingsRoute._addFileChildren(
  AdminTrainingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  TrainingsRoute: TrainingsRouteWithChildren,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTrainingsRoute: AdminTrainingsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
